import {mkdirSync,readFileSync,writeFileSync,cpSync} from 'node:fs';
import {collection} from '../src/collection.mjs';
import {getCollectionBrokers} from '../src/catalog.mjs';
import {BrokerCard,Comparison,Summary,escapeHtml as e,svg,arrow} from '../src/components.mjs';
const rows=getCollectionBrokers(collection);
const faqs=[
 ['What is the best forex broker in 2026?','There is no single best broker for every trader. Start with the regulated entity available in your country, then compare platforms, total trading costs and account conditions. This page is a design demonstration; its numbered order is illustrative.'],
 ['How does FXRebate rank forex brokers?','The proposed collection considers regulation, trading costs, platform choice, account conditions and cashback availability. The demo does not use a verified numeric scoring system. Final rankings and methodology need editorial approval.'],
 ['Which forex broker is best for beginners?','Look for a usable demo account, clear education, reliable support and an account size you can manage. Test the platform before depositing. A beginner category should be based on a reviewed comparison rather than a rebate amount alone.'],
 ['Which broker has the lowest trading costs?','Compare spreads, commissions, swaps and any account fees for the instruments you actually trade. Subtract eligible cashback only after checking its terms. A Raw account may be cheaper for one strategy but not another.'],
 ['Are forex rebates available with all brokers?','No. Availability depends on the broker partnership, your country, legal entity, account and instruments. Check the current FXRebate profile before opening or linking an account.'],
 ['Does FXRebate change my broker trading conditions?','Check the specific partnership terms. The IC Markets FXRebate profile states that its rebate provision is independent of your agreement with the broker. Do not assume the same terms apply to every partner or account.'],
 ['How do forex broker rebates work?','A broker pays a partner commission to FXRebate. FXRebate returns part of that commission to eligible traders according to the partnership schedule. Rates may be expressed per lot, in points or pips, or as a share of spread or commission.'],
 ['How often are broker rankings updated?','A production collection should be reviewed whenever broker terms or partnerships change, with its last review date shown. This demo was assembled on 8 October 2026 and is not an approved live ranking.']
];
const criteria=[['shield','Regulation & safety','Check the legal entity, regulator and protections available where you live.'],['coins','Total trading costs','Consider spreads, commissions and swaps together with eligible cashback.'],['layers','Platforms & conditions','Match platforms, order types and account conditions to your trading style.'],['check','Access & reliability','Review funding, support, account accessibility and partnership eligibility.']];
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Best Forex Brokers 2026 | FXRebate — Design Preview</title><meta name="description" content="Explore six forex brokers, compare platforms and account conditions, and discover FXRebate cashback options. Client design preview."><meta name="robots" content="noindex,nofollow"><meta property="og:title" content="Best Forex Brokers 2026 | FXRebate"><meta property="og:description" content="A clearer way to compare brokers. A smarter way to explore cashback."><meta property="og:type" content="website"><meta name="theme-color" content="#073d50"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><script src="/client.js" defer></script></head><body>
<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="container header-inner"><a href="https://fxrebate.eu" aria-label="FXRebate home" class="brand"><img src="/assets/fxrebate.png" alt="FXRebate — where every trade matters" width="192" height="63"></a><nav aria-label="Main navigation"><a class="current" href="#top-brokers">Brokers</a><a href="#cashback-explained">How cashback works</a><a href="#methodology">Our approach</a></nav><a class="header-cta" href="#comparison">Compare brokers <span aria-hidden="true">↗</span></a></div></header>
<main id="main" class="container"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="https://fxrebate.eu">Home</a><span aria-hidden="true">/</span><a href="https://fxrebate.eu/brokers">Brokers</a><span aria-hidden="true">/</span><span aria-current="page">Best Forex Brokers</span></nav>
<section class="hero" aria-labelledby="page-title"><div><p class="eyebrow"><span class="status-dot" aria-hidden="true"></span> THE FXREBATE BROKER SHORTLIST</p><h1 id="page-title">Best Forex Brokers <span>2026</span></h1><p class="hero-intro">Find the right fit for your trading. Compare broker essentials, explore platform choices and see what FXRebate gives back.</p><div class="hero-meta"><span>Design preview · ${collection.updated}</span><span class="meta-divider" aria-hidden="true"></span><a href="#methodology" data-event="methodology_click">How we compare brokers <span aria-hidden="true">↗</span></a></div></div><aside class="hero-note"><span class="note-icon">${svg('coins')}</span><h2>Your trades.<br>Your cashback.</h2><p>Broker choice matters.<br>So does what you get back.</p><a href="#cashback-explained">Discover the FXRebate advantage ${arrow}</a></aside></section>
<div class="preview-note"><span class="preview-pill">CLIENT PREVIEW</span><p>Illustrative shortlist and editorial order. Broker terms and eligibility vary by account, entity and country.</p></div>
<section id="top-brokers" class="top-section" aria-labelledby="top-title"><div class="section-heading"><div><p class="eyebrow">01 / THE SHORTLIST</p><h2 id="top-title">Six brokers. A clearer choice.</h2></div><a class="text-link" href="#comparison">Compare side by side ${arrow}</a></div><div class="filter-bar"><div role="group" aria-label="Filter featured brokers"><button type="button" class="filter active" data-filter="all" aria-pressed="true">All brokers <span>6</span></button><button type="button" class="filter" data-filter="MT5" aria-pressed="false">MT5</button><button type="button" class="filter" data-filter="cTrader" aria-pressed="false">cTrader</button><button type="button" class="filter" data-filter="commission" aria-pressed="false">Commission cashback</button></div><span class="filter-count" role="status" aria-live="polite">Showing 6 brokers</span></div><div class="broker-grid">${rows.map(({broker,placement})=>BrokerCard(broker,placement)).join('')}</div><p class="data-note">Ratings shown are public FXRebate profile ratings. Platform data comes from the existing broker catalog. Account-specific offers are examples from public profiles; always check current terms.</p></section>
<section id="comparison" class="page-section" aria-labelledby="compare-title"><div class="section-heading"><div><p class="eyebrow">02 / AT A GLANCE</p><h2 id="compare-title">The details, side by side.</h2></div><span class="section-aside">Same shortlist. One simple comparison.</span></div>${Comparison(rows)}<p class="data-note">Minimum deposits and regulations depend on the entity and account. “See profile” means a verified value was unavailable for this preview.</p></section>
<section id="methodology" class="page-section methodology" aria-labelledby="method-title"><div class="section-heading"><div><p class="eyebrow">03 / OUR APPROACH</p><h2 id="method-title">More than a cashback number.</h2></div></div><p class="section-intro">The right broker brings together regulation, costs, tools and suitability. These are the criteria proposed for the production collection; the demo order is not a scored ranking.</p><div class="criteria-grid">${criteria.map(([i,h,p])=>`<article>${svg(i)}<h3>${h}</h3><p>${p}</p></article>`).join('')}</div></section>
<section id="broker-notes" class="page-section" aria-labelledby="notes-title"><div class="section-heading"><div><p class="eyebrow">04 / A CLOSER LOOK</p><h2 id="notes-title">Find your kind of broker.</h2></div><span class="section-aside">The context behind the cards.</span></div><div class="summaries">${rows.map(({broker,placement})=>Summary(broker,placement)).join('')}</div></section>
<section class="page-section match-section" aria-labelledby="match-title"><div><p class="eyebrow">05 / YOUR TRADING, YOUR CHOICE</p><h2 id="match-title">What matters<br>most to you?</h2><p>Start with a priority.<br>Then explore the full picture.</p><small>Example categories for this preview.</small></div><div class="match-list">${rows.map(({broker:b,placement:p})=>`<a href="${e(b.profileUrl)}" data-event="broker_profile_click" data-broker-id="${e(b.id)}"><span>${e(p.bestFor)}</span><strong>${e(b.name)} ${arrow}</strong></a>`).join('')}</div></section>
<section class="page-section choose-section" aria-labelledby="choose-title"><div class="section-heading"><div><p class="eyebrow">06 / BEFORE YOU DECIDE</p><h2 id="choose-title">A few checks go a long way.</h2></div></div><div class="choose-grid">${[['01','Check your entity','Verify the regulator and legal entity available in your country, and the protections it offers.'],['02','Calculate the total cost','Include spreads, commission, overnight swaps and any funding or withdrawal fees.'],['03','Try the trading experience','Use a demo account to test platforms, execution tools and support before committing.'],['04','Read the account terms','Review account types, deposits, withdrawals and rebate eligibility for your setup.']].map(([n,h,p])=>`<article><span>${n}</span><h3>${h}</h3><p>${p}</p></article>`).join('')}</div></section>
<section id="cashback-explained" class="cashback-explainer page-section" aria-labelledby="cashback-title"><div class="cashback-explainer-top"><div><p class="eyebrow">THE FXREBATE ADVANTAGE</p><h2 id="cashback-title">Keep more from<br>the trades you make.</h2></div><p>Eligible trades can earn cashback through FXRebate. The amount and payout route depend on your broker, account and partnership terms.</p></div><ol class="cashback-steps"><li><span>01</span><h3>You trade with your broker</h3><p>Through an eligible linked account.</p></li><li><span>02</span><h3>The broker pays FXRebate</h3><p>A commission under the partnership.</p></li><li><span>03</span><h3>FXRebate shares it with you</h3><p>Cashback according to the offer terms.</p></li></ol><div class="cashback-explainer-bottom"><span>Cashback reduces eligible costs. It does not remove trading risk.</span><a href="#top-brokers">Explore cashback brokers ${arrow}</a></div></section>
<section id="faq" class="page-section faq-section" aria-labelledby="faq-title"><div><p class="eyebrow">07 / GOOD QUESTIONS</p><h2 id="faq-title">A little more clarity.</h2><p>Broker choice and cashback,<br>without the guesswork.</p></div><div class="faq-list">${faqs.map(([q,a],i)=>`<details data-faq="${i}"><summary>${e(q)}<span class="faq-plus" aria-hidden="true">+</span></summary><div class="faq-answer"><p>${e(a)}</p></div></details>`).join('')}</div></section>
<div class="editorial"><div>${svg('shield')}<strong>Transparent by design</strong></div><p>Client design preview · Updated ${collection.updated}. Public profile facts captured on 8 October; platform catalog snapshot dated 12 August 2026. Editorial placements are demonstration content. Final rankings, ratings policy and data require FXRebate review.</p><a href="#methodology">View methodology ${arrow}</a></div>
</main><footer class="site-footer"><div class="container"><div class="footer-top"><a href="https://fxrebate.eu" class="brand"><img src="/assets/fxrebate.png" alt="FXRebate" width="174" height="57" loading="lazy"></a><span>Where every trade matters.</span><a href="#top-brokers">Back to the shortlist ↑</a></div><div class="footer-legal"><p><strong>Risk disclosure.</strong> Forex and CFD trading involves a high risk of losing money and may not be suitable for everyone. Cashback does not offset this risk. This preview is informational and is not personalized investment advice.</p><p><strong>Advertising disclosure.</strong> FXRebate may receive partner commissions from brokers and returns a portion to eligible traders. Availability and terms vary. The demo ranking is illustrative.</p></div><div class="footer-bottom"><span>© 2026 FXRebate</span><span>Client concept preview · Not the live FXRebate website</span></div></div></footer>
</body></html>`;
mkdirSync('output/site/brokers/best-forex-brokers',{recursive:true});
writeFileSync('output/site/index.html',html);writeFileSync('output/site/brokers/best-forex-brokers/index.html',html);
cpSync('assets','output/site/assets',{recursive:true});
for(const [source,target] of [['src/styles.css','styles.css'],['src/client.js','client.js']])writeFileSync(`output/site/${target}`,readFileSync(source));
writeFileSync('output/site/robots.txt','User-agent: *\nDisallow: /\n');
writeFileSync('output/site/vercel.json',JSON.stringify({cleanUrls:true,headers:[{source:'/(.*)',headers:[{key:'X-Robots-Tag',value:'noindex, nofollow'},{key:'X-Content-Type-Options',value:'nosniff'}]}]},null,2));
console.log(`Built ${rows.length} catalog-backed cards → output/site/brokers/best-forex-brokers/index.html`);
