// Placement content is deliberately separate from broker master facts.
// Client demo order: this is not an approved FXRebate ranking or numeric scoring model.
export const collection = {
  id: 'best_forex_brokers', title: 'Best Forex Brokers 2026', updated: '8 October 2026',
  placements: [
    {brokerId:'ic-markets',rank:1,bestFor:'Active traders',shortVerdict:'A choice of Raw Spread and Standard accounts, with MT4, MT5 and cTrader support.',highlights:['Raw Spread account choice','Three established platforms'],overview:'For traders who already know their platform, the choice between Standard and Raw Spread accounts makes it easier to compare how spread and commission costs fit a strategy.',consider:'Rebate eligibility varies by entity and country. The FXRebate profile lists restrictions for EU and Romanian clients.'},
    {brokerId:'fp-markets',rank:2,bestFor:'Platform choice',shortVerdict:'MetaTrader and cTrader options, with a choice of Standard and Raw accounts.',highlights:['MT4, MT5 and cTrader','Standard and Raw accounts'],overview:'Platform choice is the starting point here. Traders can explore familiar MetaTrader tools or cTrader, then review the account structure and total trading costs in the full profile.',consider:'Account and rebate availability depend on the broker entity and your residence. Confirm the current schedule before applying.'},
    {brokerId:'xm',rank:3,bestFor:'Account flexibility',shortVerdict:'Several account options across MT4 and MT5, with account-specific cashback schedules.',highlights:['Multiple account options','MT4 and MT5 support'],overview:'The catalog documents Micro, Standard and other account options. This is a useful comparison for traders looking to understand how account size, pricing and rebate terms work together.',consider:'Micro-lot rebates use different units. Compare equivalent trade sizes and confirm which account terms apply to you.'},
    {brokerId:'fxpro',rank:4,bestFor:'Cashback variety',shortVerdict:'Spread-based and pip-based cashback options across different trading accounts.',highlights:['Different rebate formats','MetaTrader and cTrader'],overview:'FxPro illustrates why a cashback comparison needs more than a single dollar figure. Its schedules include a share of the spread and pip-based rates, depending on the account and instrument.',consider:'A spread percentage is not directly comparable with a dollar-per-lot rate. Review the instrument-specific table.'},
    {brokerId:'fusion-markets',rank:5,bestFor:'Payout options',shortVerdict:'Classic and Zero accounts with different cashback and automatic rebate schedules.',highlights:['Classic and Zero accounts','Automatic rebate options'],overview:'Fusion Markets provides a useful example of account-specific payout choices. Compare the Classic and Zero schedules and their automatic rebate options before choosing a setup.',consider:'Rates are quoted in points per lot. Confirm the conversion, account eligibility and payout route in the full profile.'},
    {brokerId:'dukascopy',rank:6,bestFor:'API trading',shortVerdict:'JForex and API account options, with commission-based cashback for eligible trades.',highlights:['JForex and API options','Commission-based cashback'],overview:'Dukascopy is included to show a different platform and rebate structure. Its JForex and API options offer a distinct alternative to MetaTrader, with cashback expressed as a share of commission.',consider:'The 35% rate applies to eligible JForex API and FIX API accounts. Other listed platforms have different rates.'}
  ].map(p=>({...p,enabled:true,displayOrder:p.rank}))
};
