export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escapeHtml;
export const arrow='<span aria-hidden="true" class="arrow">↗</span>';
export const icon=(name)=>({shield:'<path d="M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6z"/><path d="m8 12 3 3 5-6"/>',layers:'<path d="m3 7 9-4 9 4-9 4zM3 12l9 4 9-4M3 17l9 4 9-4"/>',coins:'<ellipse cx="9" cy="6" rx="6" ry="3"/><path d="M3 6v6c0 4 12 4 12 0V6M3 11v6c0 4 12 4 12 0v-5M18 8c4 1 4 5 0 6M18 14c4 1 4 5 0 6"/>',check:'<path d="m5 12 4 4L19 6"/>'}[name]??'');
export const svg=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true">${icon(name)}</svg>`;
export function logo(b){return b.logo?`<img src="${e(b.logo)}" alt="${e(b.name)}" width="132" height="42" loading="lazy">`:`<span class="logo-fallback">${e(b.name)}</span>`;}
export function rating(b){return b.rating?`<div class="rating" aria-label="Public FXRebate profile rating: ${e(b.rating)} out of 5"><span aria-hidden="true">★</span> ${b.rating.toFixed(1)}<small>/ 5</small></div>`:'';}
export function offer(b){return `<strong>${e(b.rebate.value)}${b.rebate.unit?` <span>${e(b.rebate.unit)}</span>`:''}</strong>`;}
export function profileLink(b,p,label='View Broker',className='broker-cta'){return `<a class="${e(className)}" href="${e(b.profileUrl)}" data-event="broker_profile_click" data-broker-id="${e(b.id)}" data-rank="${p.rank}" aria-label="${e(label)} — ${e(b.name)}">${e(label)} ${arrow}</a>`;}
export function BrokerCard(b,p){return `<article class="broker-card${p.rank===1?' featured':''}" data-broker-id="${e(b.id)}" data-platforms="${e(b.platforms.join(','))}" data-rebate-type="${e(b.rebate.type)}" data-rank="${p.rank}">
<div class="rank-line"><span class="rank"><small>#</small>${p.rank.toString().padStart(2,'0')}</span><span class="best-for"><span>BEST FOR</span> ${e(p.bestFor)}</span></div>
<div class="identity"><div class="logo-box">${logo(b)}</div>${rating(b)}<h3>${e(b.name)}</h3></div>
<p class="verdict">${e(p.shortVerdict)}</p>
<dl class="facts"><div><dt>Regulation</dt><dd title="${e(b.regulators.join(' · '))}">${e(b.regulators.slice(0,2).join(' · ')||'See profile')}${b.regulators.length>2?` <span class="more">+${b.regulators.length-2}</span>`:''}</dd></div><div><dt>Min. deposit</dt><dd>${e(b.minimumDeposit)}</dd></div><div><dt>Platforms</dt><dd>${e(b.platforms.slice(0,3).join(' · ')||'See profile')}</dd></div></dl>
<div class="cashback"><div class="cashback-label">${svg('coins')} FXREBATE CASHBACK <a href="${e(b.profileUrl)}" aria-label="See cashback rates for ${e(b.name)}" data-event="rebate_offer_click" data-broker-id="${e(b.id)}">↗</a></div>${offer(b)}<p>${e(b.rebate.note)}</p></div>
<ul class="highlights">${(p.highlights??[]).slice(0,2).map(h=>`<li><span aria-hidden="true">✓</span> ${e(h)}</li>`).join('')}</ul>
${profileLink(b,p)}
</article>`;}
export function Comparison(rows){return `<div class="comparison"><table><caption class="sr-only">Compare featured forex brokers and FXRebate cashback offers</caption><thead><tr>${['Broker','Best for','Profile rating','Min. deposit','Platforms','FXRebate cashback'].map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(({broker:b,placement:p})=>`<tr><th scope="row"><a href="${e(b.profileUrl)}" data-event="broker_profile_click" data-broker-id="${e(b.id)}"><span class="table-rank">${p.rank.toString().padStart(2,'0')}</span>${e(b.name)} <span aria-hidden="true">↗</span></a></th><td data-label="Best for">${e(p.bestFor)}</td><td data-label="Profile rating">${b.rating?`<span class="star">★</span> ${b.rating.toFixed(1)} / 5`:'Not shown'}</td><td data-label="Min. deposit">${e(b.minimumDeposit)}</td><td data-label="Platforms">${e(b.platforms.slice(0,3).join(' · '))}</td><td data-label="FXRebate cashback">${offer(b)}</td></tr>`).join('')}</tbody></table></div>`;}
export function Summary(b,p){return `<article class="summary"><div class="summary-title"><span class="summary-rank">${p.rank.toString().padStart(2,'0')}</span><div><p class="eyebrow">BEST FOR ${e(p.bestFor)}</p><h3>${e(b.name)}</h3></div><div class="summary-logo">${logo(b)}</div></div><p>${e(p.overview)}</p><div class="summary-columns"><div><h4>Why explore it</h4><ul class="highlights">${p.highlights.map(h=>`<li><span aria-hidden="true">✓</span> ${e(h)}</li>`).join('')}</ul></div><div><h4>Things to consider</h4><p>${e(p.consider)}</p></div></div><div class="summary-bottom"><span><span class="cashback-dot" aria-hidden="true"></span> ${e(b.rebate.value)} ${e(b.rebate.unit??'')} · ${e(b.rebate.note)}</span>${profileLink(b,p,'Full broker profile','text-link')}</div></article>`;}
